name: github-release

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: tag-new-version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: dotnet msbuild $(find . -name "*.csproj" -print -quit) -getProperty:Version
      - if: ${{ steps.tag-new-version.outputs.tag }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - if: ${{ steps.tag-new-version.outputs.tag }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ steps.tag-new-version.outputs.tag }}
